# Generated by Django 4.1.1 on 2022-09-20 08:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadsmodel',
            name='created_at',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='threadsmodel',
            name='updated_at',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='commentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('tread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.threadsmodel')),
            ],
        ),
    ]
