# Generated by Django 4.1.1 on 2022-09-20 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_threadsmodel_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='commentsModel',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='threadsModel',
            new_name='Thread',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='tread',
            new_name='thread',
        ),
    ]
